get_transactions = [
    {
        "transaction_type": 1,
        "transaction_date": "2022-01-15T19:20:30",
        "transaction_type_description": "Venda produtor",
        "seller_name": "Joao Silva",
        "transaction_value": 100.0,
        "product_description": "CURSO DE ANGULAR",
        "id": 1,
        "comission": None,
        "signal": True,
    },
    {
        "transaction_type": 1,
        "transaction_date": "2022-01-15T19:20:30",
        "transaction_type_description": "Venda produtor",
        "seller_name": "Joao Silva",
        "transaction_value": 200.0,
        "product_description": "CURSO DE PYTHON",
        "id": 2,
        "comission": None,
        "signal": True,
    },
    {
        "transaction_type": 2,
        "transaction_date": "2022-01-15T19:20:30",
        "transaction_type_description": "Venda afiliado",
        "seller_name": "Maria Silva",
        "transaction_value": 300.0,
        "product_description": "CURSO DE JAVA",
        "id": 3,
        "comission": None,
        "signal": True,
    },
    {
        "transaction_type": 3,
        "transaction_date": "2022-01-15T19:20:30",
        "transaction_type_description": "Comissão paga",
        "seller_name": "Maria Silva",
        "transaction_value": 300.0,
        "product_description": "CURSO DE JAVA",
        "id": 4,
        "comission": 10.0,
        "signal": False,
    },
    {
        "transaction_type": 4,
        "transaction_date": "2022-01-15T19:20:30",
        "transaction_type_description": "Comissão recebida",
        "seller_name": "Maria Silva",
        "transaction_value": 300.0,
        "product_description": "CURSO DE JAVA",
        "id": 5,
        "comission": 10.0,
        "signal": True,
    },
]

get_transactions_with_search = [
    {
        "transaction_type": 1,
        "transaction_date": "2022-01-15T19:20:30",
        "transaction_type_description": "Venda produtor",
        "seller_name": "Joao Silva",
        "transaction_value": 100.0,
        "product_description": "CURSO DE ANGULAR",
        "id": 1,
        "comission": None,
        "signal": True,
    },
    {
        "transaction_type": 1,
        "transaction_date": "2022-01-15T19:20:30",
        "transaction_type_description": "Venda produtor",
        "seller_name": "Joao Silva",
        "transaction_value": 200.0,
        "product_description": "CURSO DE PYTHON",
        "id": 2,
        "comission": None,
        "signal": True,
    },
]
